name: Check specific version

on:
  workflow_dispatch:
    inputs:
      channel:
        description: The channel to use
        required: true
        type: string
        default: stable
      profile:
        description: The profile to use
        required: true
        type: choice
        options:
          - 'minimal'
          - 'default'
          - 'complete'
        default: 'minimal'
      components:
        description: The components to install
        required: false
        type: string
      subcommands:
        description: The subcommands to install
        required: false
        type: string
      cache:
        description: Whether to cache the binaries
        required: true
        type: choice
        options:
          - 'false'
          - 'binstall'
          - 'all'
        default: 'false'

env:
  NODE_VERSION: 24

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build Typescript
        run: npm run build
      - name: Package with NCC
        run: npm run package
      - name: Upload built action
        uses: actions/upload-artifact@v4
        with:
          name: built-action
          path: |
            dist/index.js
            .github/
            action.yml
          retention-days: 1
          if-no-files-found: error
          include-hidden-files: true
  test_action:
    needs: build
    runs-on: ${{ matrix.os }}
    name: Test action for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Download built action
        uses: actions/download-artifact@v5
        with:
          name: built-action
      - name: Test action
        id: build
        uses: ./
        with:
          channel: ${{ inputs.channel }}
          profile: ${{ inputs.profile }}
          components: ${{ inputs.components }}
          subcommands: ${{ inputs.subcommands }}
          cache: ${{ inputs.cache }}
